### ISSUE TITLE
X-GSN setup and running

### ISSUE THREAD

**Issue by premjayaraman** [OpenIotOrg/openiot#10]
Error running x-gsn
1. In eclipse, when using the m2e plugin, the pom files shows the following errors
   (Eclipse SDK Version: 3.7.2)

maven-dependency-plugin (goals "copy-dependencies", "unpack") is not supported by m2e.  pom.xml /xgsn   line 44 Maven Project Build Lifecycle Mapping Problem

See image below to where the error points too.
![pom-error](https://f.cloud.github.com/assets/2141439/1404456/634ab776-3d07-11e3-9610-9c4f4e7cafd5.png)
1. The bat file to start GSN under windows results in the error 
   Error: could not find or load main class org.openiot.gsn.Main

I updated the java path to my local installation.
The FOR loop line of the batch file seems to look for jars but my target has no jar files. It only has class files.

I am missing a maven goal to generate the jar file for x-gsn?

Screenshot of error below

![gsn-start-error](https://f.cloud.github.com/assets/2141439/1404472/bbbf5ede-3d07-11e3-9f19-37db0b3c8338.png)

I also request, the wiki and cookbook be updated on the right instructions to run the GSN server.

**Comment by hylkevds** [comment]
Can you try applying the following fix to the pom.xml to see if it fixes the problem?
http://stackoverflow.com/questions/8706017/maven-dependency-plugin-goals-copy-dependencies-unpack-is-not-supported-b/12109018#12109018

**Comment by premjayaraman** [comment]
thanks hylke for the link. I tried those solutions and a few others. Here are some observations
1. The jixb-m2e connector does not want to install on my current version of eclipse and m2e (there seems to be some version mismatch)
2. The above solutions are good to mostly ignore those build options in eclupse but not to get maven m2e plugin to include them and perform binding and packaging. Also, the jixb in GSN has configuration lines to bind files in a specific directory. I tried searching online but could not find a way to include config information in <lifecycleMappingMetadata>.
3. I managed to run GSN from cmd using maven command after playing around with the start.bat and stop.bat file. That works well. I will shortly checkin the updated .bat files.

The question is now, what version of eclipse, m2e and jixb converter was used to setup GSN. That way we can resort to a common operating platform.

**Comment by sarni** [comment]
For generating the jar files in the '**target**' folder, you need to run the **package** phase in maven:

```
mvn package
```

**package** : takes the compiled code and packages it in its distributable format, such as a JAR

This phase automatically runs all the necessary phases for preparing X-GSN to be executed including the following procedures:
- Compile
- Binding XML beans descriptions to Java through JiBX
- Generating JAR file
- Copying all dependencies from local Maven repository to target folder in order to be included in the class path for the execution of X-GSN.
