### ISSUE TITLE
Wrong Download Link for VM

### ISSUE THREAD

**Issue by rhzg** [OpenIotOrg/openiot#102]
the first link of the two download links for the latest version of the virtual machine still links to the old version.

**Comment by rhzg** [comment]
actually the link is correct but it points to two files but you can not read the version until you start the download, because the version number is at the end of the filename and the name is too long for the display

**Comment by nkef** [comment]
Hi Reinhard,

This is the case if you display the available downloads in grid view. If you hit list view the full descreption apears.

**Comment by nkef** [comment]
I have added a direct link to the file so as to avoid any confusion.
