### ISSUE TITLE
Start Jboss error 

### ISSUE THREAD

**Issue by wengjb** [OpenIotOrg/openiot#107]
hello eveyrone.A question with Jboss start error.I restart oracle vm and restart Jboss server. Also tips this,

**Comment by jpcik** [comment]
please indicate what type of error and include the correponding error log

**Comment by wengjb** [comment]
I was looked the log. the last line tip:  12:18:46,973 ERROR [org.jboss.as] (Controller Boot Thread) JBAS015875: JBoss AS 7.1.1.Final "Brontes" started (with errors) in 41831ms - Started 220 of 305 services (8 services failed or missing dependencies, 76 services are passive or on-demand)
and it call me "  Unable to remove  '.../virtuoso.lck' " didn't found this file   , but i found this file in that dir.

**Comment by wengjb** [comment]
I was looked the log. the last line tip:  12:18:46,973 ERROR [org.jboss.as] (Controller Boot Thread) JBAS015875: JBoss AS 7.1.1.Final "Brontes" started (with errors) in 41831ms - Started 220 of 305 services (8 services failed or missing dependencies, 76 services are passive or on-demand)
and it call me "  Unable to remove  '.../virtuoso.lck' " didn't found this file   , but i found this file in that dir.

**Comment by wengjb** [comment]
I was looked the log. the last line tip:  12:18:46,973 ERROR [org.jboss.as] (Controller Boot Thread) JBAS015875: JBoss AS 7.1.1.Final "Brontes" started (with errors) in 41831ms - Started 220 of 305 services (8 services failed or missing dependencies, 76 services are passive or on-demand)
and it call me "  Unable to remove  '.../virtuoso.lck' " didn't found this file   , but i found this file in that dir.

**Comment by wengjb** [comment]
I was looked the log. the last line tip:  12:18:46,973 ERROR [org.jboss.as] (Controller Boot Thread) JBAS015875: JBoss AS 7.1.1.Final "Brontes" started (with errors) in 41831ms - Started 220 of 305 services (8 services failed or missing dependencies, 76 services are passive or on-demand)
and it call me "  Unable to remove  '.../virtuoso.lck' " didn't found this file   , but i found this file in that dir.

**Comment by wengjb** [comment]
12:20:51 { Loading plugin 1: Type `plain', file `wikiv' in `/media/openiot/virtuoso-opensource-7/lib/virtuoso/hosting'
12:20:51   FAILED  plugin 1: Unable to locate file }
12:20:51 { Loading plugin 2: Type `plain', file `mediawiki' in `/media/openiot/virtuoso-opensource-7/lib/virtuoso/hosting'
12:20:51   FAILED  plugin 2: Unable to locate file }
12:20:51 { Loading plugin 3: Type `plain', file `creolewiki' in `/media/openiot/virtuoso-opensource-7/lib/virtuoso/hosting'
12:20:51   FAILED  plugin 3: Unable to locate file }
12:20:51 Unable to lock file /media/openiot/virtuoso-opensource-7/var/lib/virtuoso/db/virtuoso.lck (Resource temporarily unavailable).
12:20:51 Virtuoso is already runnning (pid 1771)
12:20:51 This probably means you either do not have permission to start
12:20:51 this server, or that virtuoso-t is already running.
12:20:51 If you are absolutely sure that this is not the case, please try
12:20:51 to remove the file /media/openiot/virtuoso-opensource-7/var/lib/virtuoso/db/virtuoso.lck and start again.
12:29:35 Checkpoint started
12:29:36 Checkpoint finished, log reused
12:29:36 Server shutdown complete
12:29:36 Unable to remove /media/openiot/virtuoso-opensource-7/var/lib/virtuoso/db/virtuoso.lck (No such file or directory)

**Comment by wengjb** [comment]
hello Jean-Paul
i removed 'virtuoso.lck' and restart these server .
and then , tips:
ERROR [org.jboss.as](Controller Boot Thread) JBAS015875: JBoss AS 7.1.1.Final "Brontes" started (with errors) in 29719ms - Started 144 of 236 services (17 services failed or missing dependencies, 74 services are passive or on-demand)
and from 'virtuoso.log'
13:17:25 { Loading plugin 1: Type `plain', file`wikiv' in `/media/openiot/virtuoso-opensource-7/lib/virtuoso/hosting'
13:17:25   FAILED  plugin 1: Unable to locate file }
13:17:25 { Loading plugin 2: Type`plain', file `mediawiki' in`/media/openiot/virtuoso-opensource-7/lib/virtuoso/hosting'
13:17:25   FAILED  plugin 2: Unable to locate file }
13:17:25 { Loading plugin 3: Type `plain', file`creolewiki' in `/media/openiot/virtuoso-opensource-7/lib/virtuoso/hosting'
13:17:25   FAILED  plugin 3: Unable to locate file };

THANKS FOR HELP

**Comment by premjayaraman** [comment]
Hello wen,
Are you using the VDK? Or is this a system installed from scratch?
This issue is mostly related to virtuoso permissions on the local directory?

Also note, Virtuoso needs to be running without any errors before you can start JBOSS.

possible fix:
Try to run virtuoso as sudo and see if this will fix the problem?

If it does start without errors, investigate the directory permissions as running with sudo is not recommended.

Also please use the link below to mailing list for developer technical discussions/support.
https://github.com/OpenIotOrg/openiot/wiki/Mailing-Lists

It is a recommended practice that github issue register is used primarily for reporting bugs.

thanks
prem

**Comment by wengjb** [comment]
thanks for help.
I removed 'virtuoso.lck', and I restart virtuoso .
and i restart jboss success.
