### ISSUE TITLE
Cannot login in CAS,RequestDefinition

### ISSUE THREAD

**Issue by asati1995** [OpenIotOrg/openiot#113]
When I tried with following
username: admin
password :secret: 
It prompts invalid username or password

**Comment by nkef** [comment]
Dear Asati, Please use the OpenIoT mailing [lists](https://github.com/OpenIotOrg/openiot/wiki/Mailing-Lists) for non-generic issues and provide more info for your issue (i.e. error messages, Components installed, enviroment etch)
