### ISSUE TITLE
fialure in deployment of Scheduler.core,SDUM.core,lsm-light.server in jboss  

### ISSUE THREAD

**Issue by asati1995** [OpenIotOrg/openiot#114]
I tried with your user-guide for installation but these above modules deployments fails

**Comment by nkef** [comment]
Dear Asati, Please use the OpenIoT mailing [lists](https://github.com/OpenIotOrg/openiot/wiki/Mailing-Lists) for non-generic issues and provide more info for your issue (i.e. error messages, Components installed, enviroment etch)
