### ISSUE TITLE
openiot , jboss

### ISSUE THREAD

**Issue by minamich1** [OpenIotOrg/openiot#115]
I have installed end user openiot but my jboss 7.1 vfs file is growing whenever my jboss server has ran, and after a while no more space ramain. can someone help me how can I fix this.(  I am new in this area please explain in detail).

**Comment by premjayaraman** [comment]
The jboss standalone installation has a log folder. Just deletr that to free up space.

Ensure jboss is stopped while doing that. The next release will have an improved logging system.

Thanks

/prem

<div>-------- Original message --------</div><div>From: minamich1 notifications@github.com </div><div>Date:15/11/2015  19:30  (GMT+10:00) </div><div>To: OpenIotOrg/openiot openiot@noreply.github.com </div><div>Subject: [openiot] openiot , jboss (#115) </div><div>
</div>I have installed end user openiot but my jboss 7.1 vfs file is growing whenever my jboss server has ran, and after a while no more space ramain. can someone help me how can I fix this.( I am new in this area please explain in detail).
