### ISSUE TITLE
Application Not Authorized to Use CAS

### ISSUE THREAD

**Issue by 9Khaled9** [OpenIotOrg/openiot#119]
Hello,
i need to intall OpenIoT on windows 7,
i successfully installed jdk1.7.0_79, then the maven apache, virtuoso 7.2.2, jboss AS 7.1.1.Final and then i downloaded the openiot...
i enabled the Lsm-light Server and the Security Management and Server, but when i try to login in http://localhost:8080/security.management page, i get this error:

**_# Application Not Authorized to Use CAS
The application you attempted to authenticate to is not authorized to use CAS._**
can any one help me?
and this is the resulting page:
![untitled](https://cloud.githubusercontent.com/assets/18437983/14640733/926bc74c-064b-11e6-9d2a-53460b10b1ad.png)
thanks in advanced

**Comment by nkef** [comment]
Hi,
Have you [enabled SSL in JBoss](https://github.com/OpenIotOrg/openiot/wiki/Installation-Guide#4-----configuring-jboss)?

**Comment by 9Khaled9** [comment]
Yes dear, i followed the installation steps step by step from thin link: https://github.com/OpenIotOrg/openiot/wiki/Installation-Guide
In step ((4) Configuring JBoss), the configuration of JBoss was successfully done and the same for the ssl enabling!!!!!!!!!!!!!! so the link https://localhost:8443 open normally...

**Comment by miguelan94** [comment]
Did you solve the problem? I need to resolve it

**Comment by ghost** [comment]
Hello Please share the solution if you solved the problem.

**Comment by 9Khaled9** [comment]
Dear Chandra, i really forgot how to resolve it, it is more then 1 year ago...
I'm really sorry dear...



Regards


Khaled AL CHABB

________________________________
