### ISSUE TITLE
Sceduler - RequestDefintion Invalid Login Cred / supplied email already exists

### ISSUE THREAD

**Issue by nflynn** [OpenIotOrg/openiot#12]
Cannot register or login (with existing login details registered) with the newly committed version of Scheduler core. This issues is seen bout using Scheduler client and through request definition web interface. This is also seen on two separate instances of the openiot install, running on two separate server.  

![003-requestdefintion-invalidlogincred-scedulerclient](https://f.cloud.github.com/assets/2598435/1426047/4558983a-4056-11e3-9f94-0753f8acbaa0.png)

**Comment by premjayaraman** [comment]
Hi Nigel and Nikos,

The bug in the code came from the introduction of property file. In the file User.java in org.openiot.scheduler.core.utils.lsmpa.entities update the line 

private static String SchedulerLsmFunctionalGraph = ""

to

private static PropertyManagement propertyManagement = new PropertyManagement();
private static String SchedulerLsmFunctionalGraph=propertyManagement.getSchedulerLsmFunctionalGraph();

This should allow user to register and login.

**Comment by stavrosp** [comment]
Hello Prem and Nigel,

I have pushed a new version to develop branch which makes use of the properties file that Nikos created. The methods that create the queries now have a graph argument. The caller of the method passes the correct value which is read from the properties file. 

The login functionality now works for both the client and the web app.
