### ISSUE TITLE
Unable to register Sensor. Please check LSM configuration in openiot.properties

### ISSUE THREAD

**Issue by 9Khaled9** [OpenIotOrg/openiot#121]
Hello guys, i can not register a Sensor Type, noting that my user (openiot) has the schemaEditor Default-Role... can any one help me???

 schemaEditor Default-Role:
![untitled3](https://cloud.githubusercontent.com/assets/18437983/14983721/981d94ac-1147-11e6-90af-1f4a9c8d9f97.png)

Error:
![untitled4](https://cloud.githubusercontent.com/assets/18437983/14983728/a6acb6f6-1147-11e6-97f2-b64a5c053243.png)

**Comment by anandmahato29** [comment]
Have you found any solution because i am have same problem. Please help i am stuck...

**Comment by 9Khaled9** [comment]
Dear anandmahato29

I faced many of problems during the installation and running OpenIoT...

The best solution i found, is to to install the pre-configured OpenIoT over Virtual Box...

you can find the guide of download, install and run Oracle Virtual Box and OpenIoT Virtual Box Image through this link:

https://github.com/OpenIotOrg/openiot/wiki/VDKv2---OpenIoT-Release-0.6.1---Virtual-Box-Setup-Guidehttps://github.com/OpenIotOrg/openiot/wiki/VDKv2---OpenIoT-Release-0.6.1---Virtual-Box-Setup-Guide

[https://avatars0.githubusercontent.com/u/4052935?v=3&s=400]https://github.com/OpenIotOrg/openiot/wiki/VDKv2---OpenIoT-Release-0.6.1---Virtual-Box-Setup-Guide

VDKv2 OpenIoT Release 0.6.1 Virtual Box Setup Guide ...https://github.com/OpenIotOrg/openiot/wiki/VDKv2---OpenIoT-Release-0.6.1---Virtual-Box-Setup-Guide
github.com
Hylke van der Schaaf edited this page Nov 5, 2015 · 28 revisions Install the oracle virtual box From the location where the VM is stored, double click the file ...

So after the installation of the 2 component and following the above guide, you can run OpenIoT properly and without problems...

Hope your problem be resolved by this guide.
