### ISSUE TITLE
MVN clean install

### ISSUE THREAD

**Issue by 9Khaled9** [OpenIotOrg/openiot#123]
Hello guys, i try to install the OpenIoT as an IoT platform to simulate a CoT scenario through getting data from sensors and forward it to the appropriate node.
During the intallation, i faced a lot of errors... The last one is the error in running **mvn clean install** in the root openiot-develop directory...
Is the openiot the best choice of my project??? or should i use an other platform??? is there any way to **overcome these errors during the installation**???
Noting that i do **not have lot of time** to finish my project...
So advice me please... with my regards.

**Comment by jbjares** [comment]
Dear 9Khaled9,
Could you please, share more details regarding your environment, used command lines, as well as the logs. By the way, I suggest you to use Pastebin to do that - copy and paste huge amount of logs and command lines :) 

Cheers

**Comment by 9Khaled9** [comment]
In fact, i faced many errors that resolved suddenly without any reason...
between these errors, running **mvn clean install**, so thank you very much...
