### ISSUE TITLE
[M2Eclipse] Build Order

### ISSUE THREAD

**Issue by jbjares** [OpenIotOrg/openiot#126]
Hi All,
After importing all the projects under the develop branch, I'm quite sure that there is a build order, as well as, happens with the deployment like exposed at this documentation: https://github.com/OpenIotOrg/openiot/wiki/Installation-Guide. Anyone know if I'm right, and if yes:

a)  I would like to know if the order is the same of the deployment?

b) Anybody have already configured the parent pom to deal with that sort of thing?

Thanks in advance.

**Comment by nkef** [comment]
Dear jbjares, Thank you for your interest please use [openiot-dev](https://github.com/OpenIotOrg/openiot/wiki/Mailing-Lists) mailing list for questions or issues that has not been identified

**Comment by nkef** [comment]
Yes you are correct. The parent pom is configured this way.

The following modules are libraries that are dependencies from other modules and needs to be installed (mvn install)

```
    <module>utils/utils.commons</module>
    <module>modules/security/security-client</module>
    <module>modules/lsm-light/lsm-light.client</module>
    <module>ui/ui.requestCommons</module>
```

the following are standalone components that needs to be paccaged (mvn package) and deployed

```
    <module>modules/security/security-server</module>
    <module>modules/security/security-management</module>
    <module>modules/lsm-light/lsm-light.server</module>
    <module>modules/x-gsn</module>
    <module>modules/sdum/sdum.core</module>
    <module>modules/sdum/sdum.client</module>
    <module>modules/scheduler/scheduler.core</module>
    <module>modules/scheduler/scheduler.client</module>
    <module>ui/ide/ide.core</module>
    <module>ui/ui.requestDefinition</module>
    <module>ui/ui.requestPresentation</module>
    <module>ui/ui.schemaeditor</module>
```

more details regarding the one by one build and deploy [here](https://github.com/OpenIotOrg/openiot/wiki/Installation-Guide/ff163a95abfcdb0a4606b92b84715cd2cdd8c7f1#7----deployment-of-the-modules-only-for-the-first-time-to-deploy-the-platform)
