### ISSUE TITLE
[security.server] Compile issue: There is no bottom.jsp

### ISSUE THREAD

**Issue by jbjares** [OpenIotOrg/openiot#127]
Hi All,
I would like to know if the file named as bottom.jsp is deprecated or placed in other location, once I can't find it, as well as, it's generating a compilation warn on eclipse. Likewise, I'm attaching the image to try to clarify what I mean. Then, I'm very thankful, if someone could support me with this issue. 

![where_is_bottom_jsp](https://cloud.githubusercontent.com/assets/1163531/15472349/8cb003f6-20f2-11e6-89f6-3c09a5f6c81a.png)

Thanks in advance.

**Comment by nkef** [comment]
Dear jbjares, Thank you for your interest please use [openiot-dev](https://github.com/OpenIotOrg/openiot/wiki/Mailing-Lists) mailing list for questions or issues that has not been identified

**Comment by jbjares** [comment]
Hi Nikos,
Fine. Thank you very much.
