### ISSUE TITLE
Fix x-gsn lsm property file

### ISSUE THREAD

**Issue by premjayaraman** [OpenIotOrg/openiot#13]
Hi Sofiane,

Can you please update x-gsn to make use of property file in the common utils folder so that updating username and pwd will stay in one single location.

Currently, the lsm_config.conf file needs to be updated everytime to match the property file in common.utils.

Thanks

**Comment by nkef** [comment]
Hi Prem,

Unfortunately x-gsn is probably the only module that will run separately from the rest of the architecture and moreover the only one that wont use JBoss. So it probably wont use the common properties. LSM could use the common properties as soon as it is configured to be deployed in JBoss.

**Comment by premjayaraman** [comment]
But cant it not use the openiot.commons.jar file as a dependency and refer to the configuration file there?

The same file is being copied over to JBOSS. Also it would be good to have a script that does this copying automatically if possible?

/prem

**Comment by nkef** [comment]
If it is not running within the JBoss container it wont find the correct path (i.e. in our case \jboss-as-7.1.1.Final\standalone\configuration). And if it is used as a separate file it wont be really using a "common" property file.

**Comment by premjayaraman** [comment]
This is also true.

Thanks for the clarification Nikos.

So is moving GSN to JBOSS an option for the future?

Regards
Prem

**Comment by nkef** [comment]
currently there is no discussion on moving GSN to JBoss. If there are any real advantages for this move we can discuss this possibility.

**Comment by sarni** [comment]
This enhancement is not possible for the moment as X-GSN runs in its own container.

**Comment by sarni** [comment]
Closing the issue as it is no more relevant.
