### ISSUE TITLE
Can't log in...

### ISSUE THREAD

**Issue by Annmeng** [OpenIotOrg/openiot#131]
**why did I sign up and log out CSA,and close the browser then log in with created user again,it pressented "not allow to use CSA...".?It seems didn't store my information i entered.How can I solve that?****Hope give me some ways to solve that.****Thanks**

**Comment by Annmeng** [comment]
op.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
23:36:46,970 ERROR [stderr](scheduler_Worker-4)        at com.sun.proxy.$Proxy7
7.reload(Unknown Source)
23:36:46,971 ERROR [stderr](scheduler_Worker-4)        at sun.reflect.Generated
MethodAccessor54.invoke(Unknown Source)
23:36:46,972 ERROR [stderr](scheduler_Worker-4)        at sun.reflect.Delegatin
gMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:36:46,973 ERROR [stderr](scheduler_Worker-4)        at java.lang.reflect.Met
hod.invoke(Method.java:606)
23:36:46,974 ERROR [stderr](scheduler_Worker-4)        at org.springframework.u
til.MethodInvoker.invoke(MethodInvoker.java:273)
23:36:46,975 ERROR [stderr](scheduler_Worker-4)        at org.springframework.s
cheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInt
ernal(MethodInvokingJobDetailFactoryBean.java:311)
23:36:46,977 ERROR [stderr](scheduler_Worker-4)        at org.springframework.s
cheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:113)
23:36:46,978 ERROR [stderr](scheduler_Worker-4)        at org.quartz.core.JobRu
nShell.run(JobRunShell.java:202)
23:36:46,979 ERROR [stderr](scheduler_Worker-4)        at org.quartz.simpl.Simp
leThreadPool$WorkerThread.run(SimpleThreadPool.java:525)
23:36:46,980 INFO  [stdout](scheduler_Worker-4) [CAS] WARN  o.o.s.o.l.LSMServic
eRegistryDaoImpl - There was a problem loading services. Returning an empty list
.
23:36:46,982 INFO  [stdout](scheduler_Worker-4) [CAS] INFO  o.o.s.o.OpenIoTServ
icesManagerImpl - Loaded 0 services.
23:38:45,940 INFO  [stdout](scheduler_Worker-5) [CAS] INFO  o.o.s.o.OpenIoTServ
icesManagerImpl - Reloading registered services.
23:38:45,942 INFO  [stdout](scheduler_Worker-5) [CAS] INFO  o.o.s.o.l.LSMServic
eRegistryDaoImpl - Reloading registered services ...
23:38:45,945 INFO  [stdout](scheduler_Worker-5) [CAS] INFO  o.o.s.oauth.lsm.LSM
OAuthManager - Using endpoint: http://localhost:8890/sparql
23:38:46,949 ERROR [stderr](scheduler_Worker-5) HttpException: -404 Failed to c
onnect to remote server
23:38:46,951 ERROR [stderr](scheduler_Worker-5)        at com.hp.hpl.jena.sparq
l.engine.http.HttpQuery.execGet(HttpQuery.java:202)
23:38:46,953 ERROR [stderr](scheduler_Worker-5)        at com.hp.hpl.jena.sparq
l.engine.http.HttpQuery.exec(HttpQuery.java:147)
23:38:46,955 ERROR [stderr](scheduler_Worker-5)        at com.hp.hpl.jena.sparq
l.engine.http.QueryEngineHTTP.execSelect(QueryEngineHTTP.java:122)
23:38:46,957 ERROR [stderr](scheduler_Worker-5)        at org.openiot.security.
oauth.lsm.LSMOAuthManager.getAllRegisteredServices(LSMOAuthManager.java:414)
23:38:46,959 ERROR [stderr](scheduler_Worker-5)        at org.openiot.security.
oauth.lsm.LSMServiceRegistryDaoImpl.load(LSMServiceRegistryDaoImpl.java:73)
23:38:46,962 ERROR [stderr](scheduler_Worker-5)        at org.openiot.security.
oauth.OpenIoTServicesManagerImpl.load(OpenIoTServicesManagerImpl.java:171)
23:38:46,964 ERROR [stderr](scheduler_Worker-5)        at org.openiot.security.
oauth.OpenIoTServicesManagerImpl.reload(OpenIoTServicesManagerImpl.java:165)
23:38:46,966 ERROR [stderr](scheduler_Worker-5)        at sun.reflect.Generated
MethodAccessor55.invoke(Unknown Source)
23:38:46,968 ERROR [stderr](scheduler_Worker-5)        at sun.reflect.Delegatin
gMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:38:46,970 ERROR [stderr](scheduler_Worker-5)        at java.lang.reflect.Met
hod.invoke(Method.java:606)
23:38:46,973 ERROR [stderr](scheduler_Worker-5)        at org.springframework.a
op.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:318)
23:38:46,975 ERROR [stderr](scheduler_Worker-5)        at org.springframework.a
op.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocati
on.java:183)
23:38:46,976 ERROR [stderr](scheduler_Worker-5)        at org.springframework.a
op.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:
150)
23:38:46,978 ERROR [stderr](scheduler_Worker-5)        at org.springframework.a
op.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.ja
va:90)
23:38:46,979 ERROR [stderr](scheduler_Worker-5)        at org.springframework.a
op.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:
172)
23:38:46,980 ERROR [stderr](scheduler_Worker-5)        at org.springframework.a
op.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
23:38:46,982 ERROR [stderr](scheduler_Worker-5)        at com.sun.proxy.$Proxy7
7.reload(Unknown Source)
23:38:46,983 ERROR [stderr](scheduler_Worker-5)        at sun.reflect.Generated
MethodAccessor54.invoke(Unknown Source)
23:38:46,984 ERROR [stderr](scheduler_Worker-5)        at sun.reflect.Delegatin
gMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:38:46,985 ERROR [stderr](scheduler_Worker-5)        at java.lang.reflect.Met
hod.invoke(Method.java:606)
23:38:46,986 ERROR [stderr](scheduler_Worker-5)        at org.springframework.u
til.MethodInvoker.invoke(MethodInvoker.java:273)
23:38:46,987 ERROR [stderr](scheduler_Worker-5)        at org.springframework.s
cheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInt
ernal(MethodInvokingJobDetailFactoryBean.java:311)
23:38:46,991 ERROR [stderr](scheduler_Worker-5)        at org.springframework.s
cheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:113)
23:38:46,992 ERROR [stderr](scheduler_Worker-5)        at org.quartz.core.JobRu
nShell.run(JobRunShell.java:202)
23:38:46,993 ERROR [stderr](scheduler_Worker-5)        at org.quartz.simpl.Simp
leThreadPool$WorkerThread.run(SimpleThreadPool.java:525)
23:38:46,994 INFO  [stdout](scheduler_Worker-5) [CAS] WARN  o.o.s.o.l.LSMServic
eRegistryDaoImpl - There was a problem loading services. Returning an empty list
.
23:38:46,996 INFO  [stdout](scheduler_Worker-5) [CAS] INFO  o.o.s.o.OpenIoTServ
icesManagerImpl - Loaded 0 services.
23:39:22,791 INFO  [stdout](http--127.0.0.1-8443-3) [CAS] ERROR o.j.c.s.o.w.OAu
th20AuthorizeController - Unknown clientId : openiot-security-manager-app
23:40:45,940 INFO  [stdout](scheduler_Worker-6) [CAS] INFO  o.o.s.o.OpenIoTServ
icesManagerImpl - Reloading registered services.
23:40:45,942 INFO  [stdout](scheduler_Worker-6) [CAS] INFO  o.o.s.o.l.LSMServic
eRegistryDaoImpl - Reloading registered services ...
23:40:45,944 INFO  [stdout](scheduler_Worker-6) [CAS] INFO  o.o.s.oauth.lsm.LSM
OAuthManager - Using endpoint: http://localhost:8890/sparql
23:40:46,949 ERROR [stderr](scheduler_Worker-6) HttpException: -404 Failed to c
onnect to remote server
23:40:46,951 ERROR [stderr](scheduler_Worker-6)        at com.hp.hpl.jena.sparq
l.engine.http.HttpQuery.execGet(HttpQuery.java:202)
23:40:46,953 ERROR [stderr](scheduler_Worker-6)        at com.hp.hpl.jena.sparq
l.engine.http.HttpQuery.exec(HttpQuery.java:147)
23:40:46,955 ERROR [stderr](scheduler_Worker-6)        at com.hp.hpl.jena.sparq
l.engine.http.QueryEngineHTTP.execSelect(QueryEngineHTTP.java:122)
23:40:46,957 ERROR [stderr](scheduler_Worker-6)        at org.openiot.security.
oauth.lsm.LSMOAuthManager.getAllRegisteredServices(LSMOAuthManager.java:414)
23:40:46,959 ERROR [stderr](scheduler_Worker-6)        at org.openiot.security.
oauth.lsm.LSMServiceRegistryDaoImpl.load(LSMServiceRegistryDaoImpl.java:73)
23:40:46,962 ERROR [stderr](scheduler_Worker-6)        at org.openiot.security.
oauth.OpenIoTServicesManagerImpl.load(OpenIoTServicesManagerImpl.java:171)
23:40:46,964 ERROR [stderr](scheduler_Worker-6)        at org.openiot.security.
oauth.OpenIoTServicesManagerImpl.reload(OpenIoTServicesManagerImpl.java:165)
23:40:46,966 ERROR [stderr](scheduler_Worker-6)        at sun.reflect.Generated
MethodAccessor55.invoke(Unknown Source)
23:40:46,968 ERROR [stderr](scheduler_Worker-6)        at sun.reflect.Delegatin
gMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:40:46,970 ERROR [stderr](scheduler_Worker-6)        at java.lang.reflect.Met
hod.invoke(Method.java:606)
23:40:46,972 ERROR [stderr](scheduler_Worker-6)        at org.springframework.a
op.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:318)
23:40:46,974 ERROR [stderr](scheduler_Worker-6)        at org.springframework.a
op.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocati
on.java:183)
23:40:46,975 ERROR [stderr](scheduler_Worker-6)        at org.springframework.a
op.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:
150)
23:40:46,977 ERROR [stderr](scheduler_Worker-6)        at org.springframework.a
op.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.ja
va:90)
23:40:46,978 ERROR [stderr](scheduler_Worker-6)        at org.springframework.a
op.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:
172)
23:40:46,979 ERROR [stderr](scheduler_Worker-6)        at org.springframework.a
op.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
23:40:46,980 ERROR [stderr](scheduler_Worker-6)        at com.sun.proxy.$Proxy7
7.reload(Unknown Source)
23:40:46,981 ERROR [stderr](scheduler_Worker-6)        at sun.reflect.Generated
MethodAccessor54.invoke(Unknown Source)
23:40:46,982 ERROR [stderr](scheduler_Worker-6)        at sun.reflect.Delegatin
gMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:40:46,983 ERROR [stderr](scheduler_Worker-6)        at java.lang.reflect.Met
hod.invoke(Method.java:606)
23:40:46,984 ERROR [stderr](scheduler_Worker-6)        at org.springframework.u
til.MethodInvoker.invoke(MethodInvoker.java:273)
23:40:46,985 ERROR [stderr](scheduler_Worker-6)        at org.springframework.s
cheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInt
ernal(MethodInvokingJobDetailFactoryBean.java:311)
23:40:46,987 ERROR [stderr](scheduler_Worker-6)        at org.springframework.s
cheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:113)
23:40:46,988 ERROR [stderr](scheduler_Worker-6)        at org.quartz.core.JobRu
nShell.run(JobRunShell.java:202)
23:40:46,989 ERROR [stderr](scheduler_Worker-6)        at org.quartz.simpl.Simp
leThreadPool$WorkerThread.run(SimpleThreadPool.java:525)
23:40:46,990 INFO  [stdout](scheduler_Worker-6) [CAS] WARN  o.o.s.o.l.LSMServic
eRegistryDaoImpl - There was a problem loading services. Returning an empty list
.
23:40:46,991 INFO  [stdout](scheduler_Worker-6) [CAS] INFO  o.o.s.o.OpenIoTServ
icesManagerImpl - Loaded 0 services.
23:42:45,940 INFO  [stdout](scheduler_Worker-7) [CAS] INFO  o.o.s.o.OpenIoTServ
icesManagerImpl - Reloading registered services.
23:42:45,942 INFO  [stdout](scheduler_Worker-7) [CAS] INFO  o.o.s.o.l.LSMServic
eRegistryDaoImpl - Reloading registered services ...
23:42:45,944 INFO  [stdout](scheduler_Worker-7) [CAS] INFO  o.o.s.oauth.lsm.LSM
OAuthManager - Using endpoint: http://localhost:8890/sparql
23:42:46,948 ERROR [stderr](scheduler_Worker-7) HttpException: -404 Failed to c
onnect to remote server
23:42:46,950 ERROR [stderr](scheduler_Worker-7)        at com.hp.hpl.jena.sparq
l.engine.http.HttpQuery.execGet(HttpQuery.java:202)
23:42:46,952 ERROR [stderr](scheduler_Worker-7)        at com.hp.hpl.jena.sparq
l.engine.http.HttpQuery.exec(HttpQuery.java:147)
23:42:46,954 ERROR [stderr](scheduler_Worker-7)        at com.hp.hpl.jena.sparq
l.engine.http.QueryEngineHTTP.execSelect(QueryEngineHTTP.java:122)
23:42:46,956 ERROR [stderr](scheduler_Worker-7)        at org.openiot.security.
oauth.lsm.LSMOAuthManager.getAllRegisteredServices(LSMOAuthManager.java:414)
23:42:46,958 ERROR [stderr](scheduler_Worker-7)        at org.openiot.security.
oauth.lsm.LSMServiceRegistryDaoImpl.load(LSMServiceRegistryDaoImpl.java:73)
23:42:46,961 ERROR [stderr](scheduler_Worker-7)        at org.openiot.security.
oauth.OpenIoTServicesManagerImpl.load(OpenIoTServicesManagerImpl.java:171)
23:42:46,963 ERROR [stderr](scheduler_Worker-7)        at org.openiot.security.
oauth.OpenIoTServicesManagerImpl.reload(OpenIoTServicesManagerImpl.java:165)
23:42:46,965 ERROR [stderr](scheduler_Worker-7)        at sun.reflect.Generated
MethodAccessor55.invoke(Unknown Source)
23:42:46,967 ERROR [stderr](scheduler_Worker-7)        at sun.reflect.Delegatin
gMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:42:46,969 ERROR [stderr](scheduler_Worker-7)        at java.lang.reflect.Met
hod.invoke(Method.java:606)
23:42:46,971 ERROR [stderr](scheduler_Worker-7)        at org.springframework.a
op.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:318)
23:42:46,973 ERROR [stderr](scheduler_Worker-7)        at org.springframework.a
op.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocati
on.java:183)
23:42:46,975 ERROR [stderr](scheduler_Worker-7)        at org.springframework.a
op.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:
150)
23:42:46,977 ERROR [stderr](scheduler_Worker-7)        at org.springframework.a
op.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.ja
va:90)
23:42:46,978 ERROR [stderr](scheduler_Worker-7)        at org.springframework.a
op.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:
172)
23:42:46,980 ERROR [stderr](scheduler_Worker-7)        at org.springframework.a
op.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
23:42:46,981 ERROR [stderr](scheduler_Worker-7)        at com.sun.proxy.$Proxy7
7.reload(Unknown Source)
23:42:46,982 ERROR [stderr](scheduler_Worker-7)        at sun.reflect.Generated
MethodAccessor54.invoke(Unknown Source)
23:42:46,983 ERROR [stderr](scheduler_Worker-7)        at sun.reflect.Delegatin
gMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:42:46,985 ERROR [stderr](scheduler_Worker-7)        at java.lang.reflect.Met
hod.invoke(Method.java:606)
23:42:46,986 ERROR [stderr](scheduler_Worker-7)        at org.springframework.u
til.MethodInvoker.invoke(MethodInvoker.java:273)
23:42:46,987 ERROR [stderr](scheduler_Worker-7)        at org.springframework.s
cheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInt
ernal(MethodInvokingJobDetailFactoryBean.java:311)
23:42:46,989 ERROR [stderr](scheduler_Worker-7)        at org.springframework.s
cheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:113)
23:42:46,991 ERROR [stderr](scheduler_Worker-7)        at org.quartz.core.JobRu
nShell.run(JobRunShell.java:202)
23:42:46,992 ERROR [stderr](scheduler_Worker-7)        at org.quartz.simpl.Simp
leThreadPool$WorkerThread.run(SimpleThreadPool.java:525)
23:42:46,993 INFO  [stdout](scheduler_Worker-7) [CAS] WARN  o.o.s.o.l.LSMServic
eRegistryDaoImpl - There was a problem loading services. Returning an empty list
.
23:42:46,995 INFO  [stdout](scheduler_Worker-7) [CAS] INFO  o.o.s.o.OpenIoTServ
icesManagerImpl - Loaded 0 services.
23:44:45,940 INFO  [stdout](scheduler_Worker-8) [CAS] INFO  o.o.s.o.OpenIoTServ
icesManagerImpl - Reloading registered services.
23:44:45,943 INFO  [stdout](scheduler_Worker-8) [CAS] INFO  o.o.s.o.l.LSMServic
eRegistryDaoImpl - Reloading registered services ...
23:44:45,946 INFO  [stdout](scheduler_Worker-8) [CAS] INFO  o.o.s.oauth.lsm.LSM
OAuthManager - Using endpoint: http://localhost:8890/sparql
23:44:46,950 ERROR [stderr](scheduler_Worker-8) HttpException: -404 Failed to c
onnect to remote server
23:44:46,952 ERROR [stderr](scheduler_Worker-8)        at com.hp.hpl.jena.sparq
l.engine.http.HttpQuery.execGet(HttpQuery.java:202)
23:44:46,954 ERROR [stderr](scheduler_Worker-8)        at com.hp.hpl.jena.sparq
l.engine.http.HttpQuery.exec(HttpQuery.java:147)
23:44:46,956 ERROR [stderr](scheduler_Worker-8)        at com.hp.hpl.jena.sparq
l.engine.http.QueryEngineHTTP.execSelect(QueryEngineHTTP.java:122)
23:44:46,959 ERROR [stderr](scheduler_Worker-8)        at org.openiot.security.
oauth.lsm.LSMOAuthManager.getAllRegisteredServices(LSMOAuthManager.java:414)
23:44:46,961 ERROR [stderr](scheduler_Worker-8)        at org.openiot.security.
oauth.lsm.LSMServiceRegistryDaoImpl.load(LSMServiceRegistryDaoImpl.java:73)
23:44:46,963 ERROR [stderr](scheduler_Worker-8)        at org.openiot.security.
oauth.OpenIoTServicesManagerImpl.load(OpenIoTServicesManagerImpl.java:171)
23:44:46,965 ERROR [stderr](scheduler_Worker-8)        at org.openiot.security.
oauth.OpenIoTServicesManagerImpl.reload(OpenIoTServicesManagerImpl.java:165)
23:44:46,968 ERROR [stderr](scheduler_Worker-8)        at sun.reflect.Generated
MethodAccessor55.invoke(Unknown Source)
23:44:46,969 ERROR [stderr](scheduler_Worker-8)        at sun.reflect.Delegatin
gMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:44:46,972 ERROR [stderr](scheduler_Worker-8)        at java.lang.reflect.Met
hod.invoke(Method.java:606)
23:44:46,973 ERROR [stderr](scheduler_Worker-8)        at org.springframework.a
op.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:318)
23:44:46,975 ERROR [stderr](scheduler_Worker-8)        at org.springframework.a
op.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocati
on.java:183)
23:44:46,977 ERROR [stderr](scheduler_Worker-8)        at org.springframework.a
op.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:
150)
23:44:46,978 ERROR [stderr](scheduler_Worker-8)        at org.springframework.a
op.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.ja
va:90)
23:44:46,979 ERROR [stderr](scheduler_Worker-8)        at org.springframework.a
op.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:
172)
23:44:46,980 ERROR [stderr](scheduler_Worker-8)        at org.springframework.a
op.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
23:44:46,982 ERROR [stderr](scheduler_Worker-8)        at com.sun.proxy.$Proxy7
7.reload(Unknown Source)
23:44:46,982 ERROR [stderr](scheduler_Worker-8)        at sun.reflect.Generated
MethodAccessor54.invoke(Unknown Source)
23:44:46,983 ERROR [stderr](scheduler_Worker-8)        at sun.reflect.Delegatin
gMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:44:46,984 ERROR [stderr](scheduler_Worker-8)        at java.lang.reflect.Met
hod.invoke(Method.java:606)
23:44:46,985 ERROR [stderr](scheduler_Worker-8)        at org.springframework.u
til.MethodInvoker.invoke(MethodInvoker.java:273)
23:44:46,986 ERROR [stderr](scheduler_Worker-8)        at org.springframework.s
cheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInt
ernal(MethodInvokingJobDetailFactoryBean.java:311)
23:44:46,987 ERROR [stderr](scheduler_Worker-8)        at org.springframework.s
cheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:113)
23:44:46,989 ERROR [stderr](scheduler_Worker-8)        at org.quartz.core.JobRu
nShell.run(JobRunShell.java:202)
23:44:46,990 ERROR [stderr](scheduler_Worker-8)        at org.quartz.simpl.Simp
leThreadPool$WorkerThread.run(SimpleThreadPool.java:525)
23:44:46,991 INFO  [stdout](scheduler_Worker-8) [CAS] WARN  o.o.s.o.l.LSMServic
eRegistryDaoImpl - There was a problem loading services. Returning an empty list
.
23:44:46,992 INFO  [stdout](scheduler_Worker-8) [CAS] INFO  o.o.s.o.OpenIoTServ
icesManagerImpl - Loaded 0 services.

**Comment by nkef** [comment]
Dear Annmeng, Thank you for your interest please use [openiot-dev](https://github.com/OpenIotOrg/openiot/wiki/Mailing-Lists) mailing list for questions or issues that has not been identified
