### ISSUE TITLE
How to push data from virtual sensor to LSM ???

### ISSUE THREAD

**Issue by 9Khaled9** [OpenIotOrg/openiot#132]
Hello, i Created Virtual Sensor XML File and the Virtual Sensors Metadata File, hence Creating and Registering a new Sensor Instance...
So how to push data from this virtual sensor to the lsm ????

**Comment by 9Khaled9** [comment]
IN other word, how to connect to a real sensor from where i will get data ????

**Comment by nkef** [comment]
Hi, could you please use the [openiot-dev](https://github.com/OpenIotOrg/openiot/wiki/Mailing-Lists) mailing list for questions. Thank you in advance.

**Comment by anandmahato29** [comment]
Can i know how you created virtual sensor XML File

**Comment by 9Khaled9** [comment]
Dear anandmahato29,

In the "1.Creation Virtual Sensor XML File" and "2.Creating Virtual Sensors Metadata file" parts of the installation guide, you can find an explanation of how to create XML file for a virtual sensor...

After creation the XML file, you must create the Meta Data file which must:

1-have the same name as the virtual sensor XML file with the extension (.metadata)

for example a virtual sensor named sensor1.xml will have an associated metadata file named sensor1.metadata.

2-be located in the same location (folder) of the XML file in: /openiot/modules/x-gsn/virtual-sensors

However, explanation process ca be found in this link:

https://github.com/OpenIotOrg/openiot/wiki/Installation-Guide#1-creating-virtual-sensor-xml-file

and

https://github.com/OpenIotOrg/openiot/wiki/Installation-Guide#2--creating-virtual-sensors-metadata-file

Good Luck
Regards

**Comment by anandmahato29** [comment]
Thanks for that...But when i am trying to use the virtual sensor in request definition it is showing no output except latitude and longitude
![e](https://cloud.githubusercontent.com/assets/22141116/18657690/1b8409b2-7f1a-11e6-80e4-91069aa800b6.png)
Hope you can help

**Comment by premjayaraman** [comment]
Hi,

the reason you dont see anything other than lat and lng is that xGSN has
not pushed any data into the system for the corresponding sensor.

Once you create the metadata and the virtual sensor files, run xGSN. It
should push some dummy data (using the sample csv data file).

Once this is successful, the request Definition will show the data that was
pushed.

regards
prem

**Comment by anandmahato29** [comment]
Hi,
 You have been a great help till now.Thank you for that.
I was trying to create arudino virtual light sensor as link given by you but i was facing problem like arduino not specified in wrapper then Arduino java file i created which is not working at all.
That's why it is not getting registed to xgsn.
and can anyone provide woking metafile and xml.
Also want to know how to use csv files to push dummy data
Help me

**Comment by 9Khaled9** [comment]
Unfortunately, this is the main problem i faced before, i didn't found a solution...

Really anandmahato29 i stopped at this step, and i didn't continue...

So Sorry

Regards
