### ISSUE TITLE
Licence unspecified ?

### ISSUE THREAD

**Issue by rzr** [OpenIotOrg/openiot#136]
Under which licence is project ?
please add a LICENSE file at top of project tree

**Comment by nkef** [comment]
Hi, This is a multi-component/projects work so the licence file exist within each component (i.e. check [here](https://github.com/OpenIotOrg/openiot/tree/develop/modules/scheduler/scheduler.core))

**Comment by rzr** [comment]
OK thx, not that a top level file could scan subdirectories licence, you can get inspiration from debian copyright format if you like this idea.
