### ISSUE TITLE
Missing Documentation For the available LSM Graphs

### ISSUE THREAD

**Issue by nkef** [OpenIotOrg/openiot#16]
Please add documentation for the existing graphs provided as a service from LSM and their purpose.

**Comment by nmqhoan** [comment]
merge with #3

**Comment by nmqhoan** [comment]
Hi Nikos,
Please find the documentation for OpenIoT existing graphs (draft) here: https://github.com/OpenIotOrg/openiot/wiki/OpenIoT-graphs.
If there are some other information need to be included, please let me know.

**Comment by nkef** [comment]
Hi Hoan, Thank you for this. Don't we also have a test graph?
