### ISSUE TITLE
Use Properties file for LSM hardcoded data

### ISSUE THREAD

**Issue by nkef** [OpenIotOrg/openiot#18]
As soon as LSM (lsm-light.server) is deployed in JBoss use the global properties file (directions on how to use it can be found [here](https://github.com/OpenIotOrg/openiot/wiki/Openiot-Commons-Library#developer-1)) to configure the hard-coded variables. 

![lsm hardcoded properties](https://f.cloud.github.com/assets/886559/1437105/79527216-4167-11e3-983c-986a7a492e67.jpg)

Moreover modify the LSM client (lsm-light.client) to automatically recognize if it is deployed in JBoss container or a common app to use the global properties file or a stand alone one.

**Comment by nmqhoan** [comment]
Hi Nikos, I will be aware of that.
Thanks for your comment.
