### ISSUE TITLE
Enabling Webservices

### ISSUE THREAD

**Issue by mjacoby** [OpenIotOrg/openiot#20]
After enabling the Webservices as described in http://sourceforge.net/apps/trac/gsn/wiki/webservice X-GSN won't neither compile nor run.
It seems that there is a missing dependency to axis2-java2wsdl in the maven project. Further, the package names of the auto-generated classes does not follow the new naming scheme starting with org.openiot.xxx.

**Comment by sarni** [comment]
Thank you for pointing to that problem. There was an error while repackaging GSN into X-GSN. 
This will be fixed.

**Comment by sarni** [comment]
These webservices are deprecated in X-GSN and will be removed. A new REST API is under development with similar functionality.

**Comment by sarni** [comment]
The deprecated web services have been removed.
