### ISSUE TITLE
Reopen previously created applications

### ISSUE THREAD

**Issue by premjayaraman** [OpenIotOrg/openiot#25]
Once the user creates a new application, validates it, saves its, logs out of the
application and logs back in using the same credentials, the following error.

![image](https://f.cloud.github.com/assets/2141439/1618045/782a5bb8-5627-11e3-9c09-8ab0fc0212ff.png)

**Comment by stavrosp** [comment]
Fixed. Might need to investigate a bit furher in order to provide a full JAXB solution. 
Check details at [MarshalOSDspecUtils](https://github.com/OpenIotOrg/openiot/blob/develop/ui/ui.requestCommons/src/main/java/org/openiot/ui/request/commons/util/MarshalOSDspecUtils.java)
