### ISSUE TITLE
LSM - GSN Interaction

### ISSUE THREAD

**Issue by premjayaraman** [OpenIotOrg/openiot#28]
Improved method (more descriptive) of telling the user the state of the logging (i.e.
instead of <login>true</login>)

![image](https://f.cloud.github.com/assets/2141439/1618084/820f6488-5628-11e3-85db-cf3f1050b4ba.png)

**Comment by sarni** [comment]
This logging information are generated by the LSM client API and not by X-GSN.
There is no control on them and cannot be disabled. They should be modified with the LSM client API.

**Comment by nmqhoan** [comment]
could you please be more specific on the logging information you want to retrieve so I improve it?

**Comment by premjayaraman** [comment]
The following are my suggestions
1. When there is an error, any useful message will be great. E.g. login to LSM failed. Hence cannot push data. Currently where there is an error, a false in xml format is printed. Hence its hard to identify the exact problem i.e. is the issue with xGSN or with LSM.
2. A logger can be used to log success messages avoiding printing the success message on the screen for every new data item. This way my terminal will not hopefully run out of memory :)

**Comment by nmqhoan** [comment]
logging information were added in the latest version of LSM client and server
