### ISSUE TITLE
Unified Logging

### ISSUE THREAD

**Issue by premjayaraman** [OpenIotOrg/openiot#32]
Is there a unified logging approach where all components can dump errors, debug messages etc?

Can we look into this and develop a structure e.g. a folder for logging and each module creating a log file with its name and timestamp maybe?

**Comment by nkef** [comment]
Most of the modules (that are running in JBoss container) uses  [LogBack](http://logback.qos.ch/) as a logging mechanism. Currently i have set them up to use this simple configuration (example from the scheduler):  [logback.xml](https://github.com/OpenIotOrg/openiot/blob/ait-sensap-develop/modules/scheduler/scheduler.core/src/main/resources/logback.xml). I have also created a complex one which will be capable of storing logs in a spesific folder, have more control etch which is this: [logback.xml complex](https://github.com/OpenIotOrg/openiot/blob/ait-sensap-develop/modules/scheduler/scheduler.core/src/main/resources/logback%28complex%29.xml) but i have not fully tested it yet (i was getting some errors but didnt had time to spend more on this). We can use it as a base thou for all the modules of OpenIoT platform. I encourage all the developers to use [LogBack](http://logback.qos.ch/) for the logging if their module doesnt currently support this functionality (standard out is generally not an acceptable solution).
