### ISSUE TITLE
Platform Errors

### ISSUE THREAD

**Issue by keithsptr** [OpenIotOrg/openiot#33]
Hi all,

I am having some errors when trying to compile the projects:

ide.core:

1) The attribute target is not defined in the component outputStylesheet
2) The attribute collapsible is not defined in the component layoutPane

ui.requestDefinition, ui.requestPresentation

1) No library found for namespace http://java.sun.com/jsf/composite/components/dialogs

2) No library found for namespace http://java.sun.com/jsf/composite/components/widgets

3) The attribute styleClass is not defined in the component layoutPane
4) The attribute header is not defined in the component layoutPane

5) The attribute readonly is not defined in the component inputNumber

Just for you to let you know I am following Prem Step by Step Developer. How can I move forward from here please?

![errors](https://f.cloud.github.com/assets/3962994/1630130/c3789116-5744-11e3-95b6-43ba299033fc.png)

Thanks

**Comment by cgeo7** [comment]
Hello, 

Apparently these errors appear on Netbeans but not on Eclipse, but you can safely set the compiler to ignore them for the moment. As far as ide.core is concerned, I have just commited a new version on the ait-sensap-develop branch which should take care of them so they dont appear at all. 
For requestDefinition and requestPresentation I have assigned the issue to Achilleas.
