### ISSUE TITLE
Deploying Scheduler in JBoss Error

### ISSUE THREAD

**Issue by keithsptr** [OpenIotOrg/openiot#34]
Hi all,

When I am trying to deploy Scheduler, I am getting the following error:

13:05:45,951 INFO  [org.jboss.as.server](DeploymentScanner-threads - 2) JBAS015870: Deploy of deployment "scheduler.core.war" was rolled back with failure message {"JBAS014671: Failed services" => {"jboss.deployment.unit.\"scheduler.core.war\".POST_MODULE" => "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"scheduler.core.war\".POST_MODULE: Failed to process phase POST_MODULE of deployment \"scheduler.core.war\""}}
13:05:46,211 INFO  [org.jboss.as.server.deployment](MSC service thread 1-1) JBAS015877: Stopped deployment scheduler.core.war in 246ms
13:05:46,260 INFO  [org.jboss.as.controller](DeploymentScanner-threads - 2) JBAS014774: Service status report
JBAS014777:   Services which failed to start:      service jboss.deployment.unit."scheduler.core.war".POST_MODULE: org.jboss.msc.service.StartException in service jboss.deployment.unit."scheduler.core.war".POST_MODULE: Failed to process phase POST_MODULE of deployment "scheduler.core.war"

13:05:46,289 ERROR [org.jboss.as.server.deployment.scanner](DeploymentScanner-threads - 1) {"JBAS014653: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-2" => {"JBAS014671: Failed services" => {"jboss.deployment.unit.\"scheduler.core.war\".POST_MODULE" => "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"scheduler.core.war\".POST_MODULE: Failed to process phase POST_MODULE of deployment \"scheduler.core.war\""}}}}

Regards,
Keith Spiteri

**Comment by nkef** [comment]
This error will be handled in the mailing list. If it is related with a bug or a permanent development environment problem we will escalate it as an issue to this list.
