### ISSUE TITLE
Logging in

### ISSUE THREAD

**Issue by keithsptr** [OpenIotOrg/openiot#35]
Hi all,

I am going to this link: http://localhost:8080/ide.core/home.jsf (see attached) and is telling me to log in.

When I press login, nothing happens... The only thing I have missing is the scheduler as I cannot seem to deploy it on JBoss.

I don't know what the problem is?

![login](https://f.cloud.github.com/assets/3962994/1631290/034a103c-5761-11e3-8708-eff367e5946f.png)

**Comment by nkef** [comment]
The login wont work without the Scheduler as the Scheduler is the module that provides this service.
