### ISSUE TITLE
Creating and deleting VirtualSensors

### ISSUE THREAD

**Issue by mjacoby** [OpenIotOrg/openiot#36]
Creating a VirtualSensor (via code or by copying a configuration XML file into /virtual-sensors) seems to keep a file handle open, so that the virtual sensor can't be removed because the config file can't be deleted. I don't think this behaviour is intended.

This problem can be fixed by closing in the FileInputStream created in line 113  in org.openiot.gsn.beans.Modifications.loadVirtualSensors(...).

**Comment by sarni** [comment]
If you have a patch, please commit it to the develop branch and I will check it.
