### ISSUE TITLE
LSM - Tomcat Issue

### ISSUE THREAD

**Issue by premjayaraman** [OpenIotOrg/openiot#39]
LSM currently uses TOMCAT. Since JBOSS runs on port 8080, running tomcat on the same port will not work. Hence, LSM Client code needs to read from a configuration file that will advise the server port number. More specifically, the file ObsConstant.java under org.openiot.lsm.utils

public final static String ServerHost = "http://localhost:8080/lsm-light.server/";

PS: I understand when LSM does get migrated to JBOSS, this issue will be solved. Until then, it would be good to have a configuration file to read all server properties in line to openiot.properties.

**Comment by nmqhoan** [comment]
Hi Prem,
I will update the code and put all the hardcode into a configuration file. The new version will be updated within this week.
