### ISSUE TITLE
GSN: lsmlibs_xxx.jar

### ISSUE THREAD

**Issue by hylkevds** [OpenIotOrg/openiot#4]
The X-GSN code currently includes lsmlibs_j6_2013-06-28.jar. 
Since the LSM code is in the same repository X-GSN should just depend on the lsm-light.client project.
This is done by adding this to the pom:

```
        <dependency>
            <groupId>org.openiot</groupId>
            <artifactId>lsm-light.client</artifactId>
            <version>0.0.1</version>
        </dependency>
```

I've tried it out, but there seems to be an incompatibility in the API which will need to be looked at too.

**Comment by sarni** [comment]
Yes, there is an incompatibility with LSM light.

**Comment by nkef** [comment]
Is it fixed?

**Comment by hylkevds** [comment]
No, the incompatibility is still there.

**Comment by premjayaraman** [comment]
Hi Sofiane,

thanks for merging the issues.

From Hoan' response, his view is, using the new LSM-Client will allow us to create new sensor types. 

This is very important for use-case demonstration and is of high priority for second review.

May I please know the current status of integration process between the client and x-gsn?

are there still some incompatibility?

thanks
prem

**Comment by sarni** [comment]
By the time of development of the first version of x-gsn's connectivity to lsm, the lsm-light module wasn't available yet so we based our development on the client API available on google code (http://code.google.com/p/deri-lsm/wiki/LSM_API_Documentation). 
The new LSM client API will be integrated in a forthcoming release of x-gsn.

**Comment by premjayaraman** [comment]
Hi Sofiane,

When is this release expected?

As ability to create new sensor types is very important.

thanks

**Comment by jpcik** [comment]
Changed xGSN to use the new LSM Api
check branch https://github.com/OpenIotOrg/openiot/tree/sensor-type-support
