### ISSUE TITLE
XGSN publish to LSM reads from lsm-config instead of sensor metadata file

### ISSUE THREAD

**Issue by premjayaraman** [OpenIotOrg/openiot#49]
org.openiot.gsn.metadata.LSM.publishSensorDataToLSM

This method updates Sensor Data to LSM by using the local lsm.properties file

But it should actually read the metagraph and datagraph from the metadatafile right.

Since there is no more user authentication, cant we get rid of the lsm-config.xml file completely?

**Comment by sarni** [comment]
Are you talking about this class?
https://github.com/OpenIotOrg/openiot/blob/develop/modules/x-gsn/src/main/java/org/openiot/gsn/metadata/LSM/LSMRepository.java

**Comment by premjayaraman** [comment]
Yes. This has been over a month since I reported this issue. Since there some changes have been made to xGSN. Could you please verify if the above is still the case i.e. configuration is read from lsm.property rather than the sensor.metadata file which also has information on data and metadata graph. Since we no longer use username and password for authentication, some code clean up might be required too.

Thanks

**Comment by jpcik** [comment]
cleaned, now the graphs are read only from the config file
