### ISSUE TITLE
Parent maven project

### ISSUE THREAD

**Issue by hylkevds** [OpenIotOrg/openiot#5]
It would be nice to have a parent maven project that automatically compiles all components in the correct order:

http://maven.apache.org/guides/mini/guide-multiple-modules.html

**Comment by nkef** [comment]
This is planed to be provided in the future.

**Comment by hylkevds** [comment]
I created a parent project pom for both the develop and security-integration branches. Executing a mvn install on this parent will compile all of OpenIoT in the correct order.

It could be that a child project is not yet added to this parent. If you notice this, either add it, or notify me so I can add it.
