### ISSUE TITLE
Scheduler Bug

### ISSUE THREAD

**Issue by premjayaraman** [OpenIotOrg/openiot#50]
Latest checkout from develop-barnch
pacakge: org.openiot.scheduler.core.utils.sparql;
File: SesameSPARQLClient

Bug Version

PropertyManagement propertyManagement = new PropertyManagement();
therepository = new SPARQLRepository(propertyManagement.getSchedulerLsmMetaGraph());

Fix
PropertyManagement propertyManagement = new PropertyManagement();
therepository = new SPARQLRepository(propertyManagement.getSdumLsmSparqlEndPoint());

Have not checked code in, as it needs further testing.

**Comment by stavrosp** [comment]
Fixed at latest ait-sensap-develop branch. Now merged to develop.
A new property: SchedulerLsmSparqlEndPoint was added both at PropertyManagement class
and at the properties file
