### ISSUE TITLE
OpenIoT Platform IP and Port Hard coded

### ISSUE THREAD

**Issue by keithsptr** [OpenIotOrg/openiot#51]
Hi all,

Just to let you know that I have found a bug in the platform itself. The ip address and the port number is hardcoded and therefore when I tried to run the platform on a server using different ip address and different port number (as 8080 is already used) it would not allow me to log in.

The following is the where these are hardcoded:
1. ide.core
2. lsm-light-client
3. scheduler.client
4. scheduler.core
5. sdum.client
6. sdum.core
7. security.webapp-demo
8. ui.requestCommons
9. ui.requestDefinition

I think that these should read from a property file and not hardcoded.

Regards,
Keith Spiteri

**Comment by nkef** [comment]
Dear Keith,
Just checked the following modules and does not contain 8080 port hard coded variables:
- ide.core,
- lsm-light.client (it contains a hard-coded variable in a "main" which is not used from the library)
- scheduler.core
- sdum.core
- ui.requestDefinition

the ui.requestcommons/ui.requestPresentation have already an issue [opened](https://github.com/OpenIotOrg/openiot/issues/43) 

Moreover `scheduler.client` and `sdum.client` are not used at the platforms deployment and they are meant to be used as an example for the developers that would like to build an SDUM and Scheduler client and they don't affect the platforms usage.

Could you please provide more details on the issue you opened? you can follow [this](https://github.com/OpenIotOrg/openiot/issues/43) as an example. 

As a general comment: before opening an issue make sure that it is valid and if something specific is identified (like in this case), to help the developers that are called to solve it,always provide details about it.

Best Regards,
Nikos Kefalakis

**Comment by keithsptr** [comment]
Hi Nikos,

Find a screenshot of 8080 of found in the code (with the help of Prem). So thats why I was not able to connect to it in a server.. :S

The Code was downloaded last week as this is from the server. The 8080 you see on screen is typed wrongly

![screenshot from 2014-02-20 16_59_18](https://f.cloud.github.com/assets/3962994/2220006/8c030238-9a48-11e3-9df4-85142fe4f97b.png)
![screenshot from 2014-02-20 17_01_43](https://f.cloud.github.com/assets/3962994/2220007/8c04a4ee-9a48-11e3-8526-adac39ea51a2.png)
![screenshot from 2014-02-20 17_01_55](https://f.cloud.github.com/assets/3962994/2220008/8c067fbc-9a48-11e3-9c95-fe8d88da8f07.png)

**Comment by nkef** [comment]
Hi Keith, the first two are in a properties file (they are not hard-coded) and the third one has already an issue open as i mentioned. is there something else hard-coded?

Nikos.

**Comment by premjayaraman** [comment]
HI Keith, adding to Nikos comments, the two main files to change the 8080 is the SchedulerAPIWapper and SDUMAPIWrapper under the requestCommons. As Nikos already mentioned, this is an open bug.

With the IDE.core.. the navigation.propoerites might need to be merged with existing property file. We need to decide this later.

Please use the properties files method Nikos pointed too to read the value from openiot.property file.

This should hopefully solve your problem as the scheduler wrapper and the sdum wrapper will then know the IP:PORT of your scheduler and SDUM you have deployed in JBOSS.
