### ISSUE TITLE
Update the LSM documentation (Tomcat->JBoss)

### ISSUE THREAD

**Issue by nkef** [OpenIotOrg/openiot#52]
Please update the LSM documentation in the Wiki (https://github.com/OpenIotOrg/openiot/wiki/Sensor-Data-Use,
https://github.com/OpenIotOrg/openiot/wiki/Sensor-Data-Develop ) especially the points where it refers to Tomcat instead of JBoss as it creates confusion

**Comment by nmqhoan** [comment]
the documentation is updated
