### ISSUE TITLE
X-GSN jar file

### ISSUE THREAD

**Issue by ghost** [OpenIotOrg/openiot#58]
Hi, 

Need help in getting/ downloading X-GSN jar file, RDFSensorSchemaEditor.

Regards, 
Surendran.

**Comment by jpcik** [comment]
Please use the issue tracker only for issues. For support and questions use the mailing list. https://github.com/OpenIotOrg/openiot/wiki/Mailing-Lists

By the way x-gsn is part of the OpenIoT code base, check the documentation in the wiki first.
