### ISSUE TITLE
What kind of Architectural Approach OpenIoT implements ?

### ISSUE THREAD

**Issue by mrsaniat** [OpenIotOrg/openiot#68]
I have some idea about SOA in small scale application. Does OpenIoT follow anything like that ? Would appreciate if anyone can provide the theoretical description of the approach that OpenIoT has taken.

**Comment by nkef** [comment]
Dear Saniat,

These kind of questions does not belong to the issue list. Please forward it at the project [mailing lists](https://github.com/OpenIotOrg/openiot/wiki/Mailing-Lists).

Thank you.
