### ISSUE TITLE
SecurityIntegration: security management web-app uses hardcoded security server url

### ISSUE THREAD

**Issue by hylkevds** [OpenIotOrg/openiot#74]
The security management web-app uses hard coded urls to the cas server:

```
https://localhost:8443/openiot-cas/oauth2.0/callbackAuthorize
```

Since my security server was deployed to security.server (since that is the artifact name), the web-app did not work.

The security management web-app also has that same url in one of its in-war ini files. Those settings should be moved to the openiot.properties config file.

**Comment by mdii** [comment]
All the settings are already externalized in the openiot.properties file (except maybe in some test classes). For the ini file, you can copy it to the JBoss config dir and under the name `web-client-security.management.ini` and modify the urls in this file.

**Comment by hylkevds** [comment]
Apparently, not all cases of that string are externalised in openiot.properties, since I changed all instances of the string "openiot-cas" in the file openiot.properties, and it still sent me to the wrong url.

There should not be a second ini file, all properties should be moved to openiot.properties.
