### ISSUE TITLE
Logout feature for CAS

### ISSUE THREAD

**Issue by premjayaraman** [OpenIotOrg/openiot#79]
I dont see a logout button. The only way i can now logout is to manually key in the URL below

https://localhost:8443/openiot-cas/logout

I can logout form the management interface but CAS gets struck with the admin user name and password

**Comment by mdii** [comment]
The feature is implemented. Please pull the last commit and test. The link can be seen only when the user is not logged in.

**Comment by premjayaraman** [comment]
thanks...

but I was more suggesting to add a  logout link under
https://localhost:8443/openiot-cas/

also in the authorisation page,
it will be good to show what is the logged in user and an option to logout and change the login if needed
