### ISSUE TITLE
GSN: Docs: Listening for sensor data using HTTP

### ISSUE THREAD

**Issue by hylkevds** [OpenIotOrg/openiot#8]
Does GSN have support for sensors that push data over HTTP (or plain TCP sockets)?
I've looked through the different wrappers, but I didn't see how to do it.

I could, of course, write a wrapper that uses jetty to start an http server, or use mina to just listen on a TCP port, but that seems the wrong way to do it.

**Comment by sarni** [comment]
You have an example here with a UDP socket, which you can easily adapt:

http://sourceforge.net/apps/trac/gsn/wiki/udp

**Comment by hylkevds** [comment]
ok, that is more or less what I was thinking about. Just have the wrapper open a port for listening.

I guess to have multiple instances for multiple sensors use the same port I can use a singleton that opens the port and hands off to the wrapper after the client has identified itself.

By the way, the UDP wrapper never closes its socket. Shouldn't it call socket.close() in dispose() ?

**Comment by sarni** [comment]
Yes, UDP wrapper has to close the socket. Fixed here a83344c

**Comment by sarni** [comment]
Closing issue as question is answered.
