### ISSUE TITLE
New Code in github Developer Branch

### ISSUE THREAD

**Issue by keithsptr** [OpenIotOrg/openiot#81]
Hi all,

I am compiling the code using mvn. I started with utils.commons and that worked perfectly.

I did mvn clean and then mvn install.

But when I try to do lsm-light, scheduler,sdum etc it gives me an error:

"Could not resolve dependencies for project ... org.openiot:utils.commons:jar:1.0.1 (compile)"

What is the way forward please?

**Comment by hylkevds** [comment]
You should be able to compile all components by giving one `mvn install` command in the root folder of the project. (The highest folder with a pom.xml)

I noticed I sometimes have to run `mvn install` twice for it to complete.

If that doesn't work, please post the complete error, not just part of it.

**Comment by keithsptr** [comment]
That worked thanks
