### ISSUE TITLE
SecurityIntegration: Services, Roles, Users & Permissions

### ISSUE THREAD

**Issue by hylkevds** [OpenIotOrg/openiot#83]
For the Security branch to be usable we need to document:
- Which Services need to be registered
- Which Permissions need to be created for these Services
- Which Roles need to be defined for each Service
- Which Permissions need to be assigned to each Role
- Which Users need to be created and assigned which Roles

**Comment by mdii** [comment]
This information is provided for every module in the _Use_ part of their documentation.

**Comment by hylkevds** [comment]
The documentation of the Sensor Schema Editor does not describe which permissions are needed to create new sensors.

**Comment by premjayaraman** [comment]
Schema Editor documentation updated.
