### ISSUE TITLE
Retrive data from virtuoso using SD&UM API

### ISSUE THREAD

**Issue by AbdulManaf** [OpenIotOrg/openiot#84]
Hi all,
am successfully deployed the lsm,scheduler,sdum,request definition, request presentation in JBOSS server. then am start GSN. and register my sensor . and log on to request definition and create a app with my sensor..and also create a line chart in request presentation..its working fine...

but am integrating my external java app to read sensor data..then
am try to fecth inserted sensor data from virtuoso using rest method in SD & UM .

but..how..???
pollForReport  method is enough for data fecthing..??????
what is userID & Application ID?

full of doubts..???

**Comment by nmqhoan** [comment]
As  I assume that you’re familiar with the SPARQL language, so if you want to read the sensor data, you can use the sparql endpoint :http://localhost:8890/sparql.

Best,
Hoan

**Comment by AbdulManaf** [comment]
yes. i know sparql
but i think to create a app using request definition. k, then my java app is send a request(http rest). and that way how to read the sensor data using this mediater app..

i want to get sensor data in json format...am allready send sensor data in json format

**Comment by AbdulManaf** [comment]
in 
ServiceDeliveryUtilityManagerRsControler.java class  
which method is used to retrive the sensor data..???

**Comment by nkef** [comment]
Hi,

You can find information regarding the SD&UM interface [here](https://github.com/OpenIotOrg/openiot/wiki/Service-Delivery-%26-Utility-Manager#api-specifications)

```
SDUManagerInterface:
---
pollForReport (applicationID: String): SdumServiceResultSet
getApplication(applicationID: String): OAMO
getService (serviceID: String): OSMO
getAvailableAppIDs (userID: String): DescriptiveIDs
getAvailableServiceIDs (applicationID: String): DescriptiveIDs
getUser (userID: String): OpenIotUser
```

Generally if you have the user ID (in the new version you retrieve the ID thru the security module (security branch) whereas in the older one (develop branch) you can get the user id by providing the user's credentials (it is going to be replaced soon by the one of the security branch)) you can use the `getAvailableAppIDs` from the SDUM [interface](https://github.com/OpenIotOrg/openiot/blob/develop/modules/sdum/sdum.core/src/main/java/org/openiot/sdum/core/rest/ServiceDeliveryUtilityManagerRsControler.java) to retrieve the registered services ([DescreptiveIDs](https://github.com/OpenIotOrg/openiot/wiki/Service-Delivery-%26-Utility-Manager#descriptiveids)) then by using the ID of the service you are interested in you can use the `pollForReport` from the SDUM [interface](https://github.com/OpenIotOrg/openiot/blob/develop/modules/sdum/sdum.core/src/main/java/org/openiot/sdum/core/rest/ServiceDeliveryUtilityManagerRsControler.java) to retrieve your data in [SdumServiceResultSet](https://github.com/OpenIotOrg/openiot/wiki/Service-Delivery-%26-Utility-Manager#sdumserviceresultset)  format (the java objects used in the interfaces mentioned above can be found [here](https://github.com/OpenIotOrg/openiot/tree/develop/utils/utils.commons/src/main/java/org/openiot/commons/sdum/serviceresultset/model))
