### ISSUE TITLE
How to Get Last inserted value from SPARQL

### ISSUE THREAD

**Issue by AbdulManaf** [OpenIotOrg/openiot#85]
Hi, all

am just insert the random values to virtuoso db...

3, 5 ,7,4,9, 0, 5

How to Get Last inserted value from SPARQL

is "5"

How ....????

MIN and MAX is not applicable...!!!

**Comment by nkef** [comment]
Dear Abdul,

please use the OpenIoT [mailing lists](https://github.com/OpenIotOrg/openiot/wiki/Mailing-Lists) for this kind of questions (generic ones that don't identify an issue/specific bug/enhancement/missing documentation etch).

Thank you in advance,
Nikos Kefalakis.
