### ISSUE TITLE
Login Request Presentation from External java application

### ISSUE THREAD

**Issue by AbdulManaf** [OpenIotOrg/openiot#86]
Hi,
i am using local setup of openIOT.
am successfully deployed the components and start my X-gsn. then connect my hardware. and try to pump data. ..its ok...am able to create a line chart using my hardware(sensor).

Qn...How to login request presentation from my external java app using rest. where is located the rest url for user login ...???

**Comment by nkef** [comment]
which branch are you using and when was it last updated? the latest version uses the [security module](https://github.com/OpenIotOrg/openiot/wiki/Security)
