### ISSUE TITLE
Bug with Request Definition Interface

### ISSUE THREAD

**Issue by premjayaraman** [OpenIotOrg/openiot#9]
Please find attached the request definition interface. When searching for a sensor after creating a new application, the screen just goes on infinitely returning no results as shown in the picture.

JBOSS does not seem to push any errors. Could you please advice what could be the possible fix for this or are we doing something incorrectly?

We are following the wiki and cookbook instructions to run the request definition interface.

![requestdef hanging](https://f.cloud.github.com/assets/2141439/1403699/c843ae72-3cf7-11e3-841c-b3e909e2ef4b.PNG)

**Comment by stavrosp** [comment]
Hello Prem,

I have also created a test application and then used Lausanne as location and 15km as search radius. The screen goes on wait state and after some time (close to 3-5 seconds) it is updated with one data source: Data sources(1).
If you click on it you get 'gsn'. A screen capture is also attached.

The lookup query of the sensor is run against Deri's virtuoso server. 

![reqdef](https://f.cloud.github.com/assets/2033433/1408557/981c2918-3d83-11e3-998e-5a8db760639a.png)

**Comment by stavrosp** [comment]
For now the URL which is used in the from clause of the SPARQL query is hardcorded. This is planned to be fixed on the coming days.

**Comment by nkef** [comment]
property files has been created for both Scheduler and SD&UM and has been committed to develop branch. Further documentation will be provided by Tuesday 29/10/13
The property file can be found here: [properties](https://github.com/OpenIotOrg/openiot/tree/develop/utils/utils.commons/src/main/resources/properties)
copy the `openiot.properties` file to the folowing path: `\JBoss_HOME\standalone\configuration`

**Comment by premjayaraman** [comment]
Hi Stavros,

thanks for the update. I spent time today with the new updated code with property files from nikos. Now when I search for a sensor I get the following error in my JBOSS app server

16:49:27,275 SEVERE [org.openiot.ui.request.commons.logging.LoggerService](http-localhost-127.0.0.1-8080-6) OpenIoT:RequestDefinition: [SEVERE] [SchedulerAPIWrapper.java:73] javax.xml.bind.JAXBException
- with linked exception:
  [java.lang.ClassNotFoundException: org.eclipse.persistence.jaxb.JAXBContextFactory from [Module "deployment.ui.requestDefinition.war:main" from Service Module Loader]]

The UI returns an error saying 

"There was an error connecting to the OpenIoT sensor discovery service"

thanks for looking into it.

Update

Output of my discover sensor using the Scheduler client / web rest api

http://localhost:8080/scheduler.core/rest/services/discoverSensors?userID=user000&latitude=46.520131&longitude=6.631622&radius=15

![reqdef-error2](https://f.cloud.github.com/assets/2141439/1426206/8532c61e-4061-11e3-96c0-3a5252486999.png)

is the above output correct?

I updated the new openiot.properties file to point to the schema demo/sensordata as currently there is no data for guest

Finally, in the query, why is the userID always user000 ? should it not be the id of the user making the request?

**Comment by stavrosp** [comment]
Hi Prem,

The code in order to use the properties file is now fixed. So it should now work from within the web app too:  Data sources(1) , 'gsn'

Yes, the output you get is correct. The userID parameter should be removed as it is not used for now from the lookup query. For now the lookup functionality returns the sensor types and their properties based on location.

**Comment by swaytz** [comment]
Hello,

I am facing the similar problem of:
On clicking request definition, UI returns an error saying :""There was an error connecting to the OpenIoT sensor discovery service"

On clicking request presentation UI returns saying " Error in registration"

May I know how the issue was solved. I have downloaded the latest files from the git. 

Thanks
