### ISSUE TITLE
Sensor Schema Editor: clicking "clear" runs the input box validation

### ISSUE THREAD

**Issue by hylkevds** [OpenIotOrg/openiot#93]
Clicking the "Clear" button in the sensor type editor runs validation on the input boxes and aborts when those validations fail. The same goes for the "Delete" button on an observed property.

Clicking those two buttons should not trigger validation, since what they are checking is supposed to be removed.

**Comment by premjayaraman** [comment]
The issue has been fixed. New updates of sensor schema editor is now in the develop branch..
