### ISSUE TITLE
Unable to get X-gsn war and ui.schemaeditor.war

### ISSUE THREAD

**Issue by ghost** [OpenIotOrg/openiot#95]
Hi, 

I just started to try Openiot and  I'm unable to get or build X-gsn war and ui.schemaeditor.war. Is there any way, that I can get war files downloadable instead of building it. And also need help in installing ui.requestCommons. Kindly help me in this.

Thanks in advance.

Surendran.

**Comment by jpcik** [comment]
Hello,

Xgsn is not meant to be packaged as a war.
It runs locally using the gsn_start as described in the docs: https://github.com/OpenIotOrg/openiot/wiki/X-GSN-Use
If it fails to compile, please provide details, e.g. what is the error

**Comment by ghost** [comment]
Hi, 

I'm getting Build Failed, when tried with command "maven package".
Error: 
[INFO] ------------------------------------------------------------------------
[INFO] BUILDING XGSN 1.1.4
[INFO] ------------------------------------------------------------------------
DOWNLOADING: HTTP://REPO.MAVEN.APACHE.ORG/MAVEN2/ORG/OPENIOT/LSM-LIGHT.CLIENT/0.0.1/LSM-LIGHT.CLIENT-0.0.1.POM
[WARNING] THE POM FOR ORG.OPENIOT:LSM-LIGHT.CLIENT:JAR:0.0.1 IS MISSING, NO DEPENDENCY INFORMATION AVAILABLE
DOWNLOADING: HTTP://REPO.MAVEN.APACHE.ORG/MAVEN2/ORG/OPENIOT/LSM-LIGHT.CLIENT/0.0.1/LSM-LIGHT.CLIENT-0.0.1.JAR
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] TOTAL TIME: 8.679S
[INFO] FINISHED AT: FRI NOV 21 17:20:41 IST 2014
[INFO] FINAL MEMORY: 8M/20M
[INFO] ------------------------------------------------------------------------
[ERROR] FAILED TO EXECUTE GOAL ON PROJECT XGSN: COULD NOT RESOLVE DEPENDENCIES FOR PROJECT ORG.OPENIOT.GSN:XGSN:JAR:1.1.4: COULD NOT FIND ARTIFACT ORG.OPENIOT:LSM-LIGHT.CLIENT:JAR:0.0.1 IN CENTRAL (HTTP://REPO.MAVEN.APACHE.ORG/MAVEN2) -> [HELP 1]
[ERROR] 
[ERROR] TO SEE THE FULL STACK TRACE OF THE ERRORS, RE-RUN MAVEN WITH THE -E SWITCH.
[ERROR] RE-RUN MAVEN USING THE -X SWITCH TO ENABLE FULL DEBUG LOGGING.
[ERROR] 
[ERROR] FOR MORE INFORMATION ABOUT THE ERRORS AND POSSIBLE SOLUTIONS, PLEASE READ THE FOLLOWING ARTICLES:
[ERROR] [HELP 1] HTTP://CWIKI.APACHE.ORG/CONFLUENCE/DISPLAY/MAVEN/DEPENDENCYRESOLUTIONEXCEPTION

Thanks, 
Surendran.

**Comment by hylkevds** [comment]
You have to build the dependencies of GSN first.
Do a `mvn install` at the root of the project (the topmost folder with a pom.xml), that will build everything.

**Comment by ghost** [comment]
Thanks, it is working now.

**Comment by fcuwang** [comment]
Hi ,

I have same error,i already did mvn install at the root of the project, but it still error.
what should i do?

**Comment by hylkevds** [comment]
What was the output of the mvn install command at the project root?

**Comment by fcuwang** [comment]
The same error again.

[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building xgsn 1.1.4
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.openiot:lsm-light.client:jar:0.0.1 is missing, no depe
ndency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.570 s
[INFO] Finished at: 2015-01-28T15:40:13+08:00
[INFO] Final Memory: 11M/220M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project xgsn: Could not resolve dependencies f
or project org.openiot.gsn:xgsn:jar:1.1.4: Failure to find org.openiot:lsm-light
.client:jar:0.0.1 in https://repo.maven.apache.org/maven2 was cached in the loca
l repository, resolution will not be reattempted until the update interval of ce
ntral has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyReso
lutionException

**Comment by hylkevds** [comment]
That's not the output of running mvn install _at the project root_ but of mvn install in the xgsn directory.
You need to build the dependencies first. Please run mvn install in the top-most directory that has a pom.xml file.

**Comment by fcuwang** [comment]
Sorry sir
Did I need to do any other step before I run mvn install?
When I want to run mvn install in the top-most directory,but it have error logs like : 

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] OpenIoT Common files ............................... SUCCESS [ 23.588 s]
[INFO] OpenIoT Security Client ............................ SUCCESS [ 43.219 s]
[INFO] OpenIoT LSM-light Client ........................... SUCCESS [01:06 min]
[INFO] OpenIoT Security server ............................ SUCCESS [01:28 min]
[INFO] OpenIoT security management web app ................ FAILURE [17:40 min]
[INFO] OpenIoT LSM-light Server ........................... SKIPPED
[INFO] xgsn ............................................... SKIPPED
[INFO] OpenIoT sdum.core .................................. SKIPPED
[INFO] OpenIoT sdum.client ................................ SKIPPED
[INFO] OpenIoT Scheduler Core ............................. SKIPPED
[INFO] OpenIoT Scheduler Client ........................... SKIPPED
[INFO] OpenIoT ide.core ................................... SKIPPED
[INFO] OpenIoT request definition/presentation commons .... SKIPPED
[INFO] OpenIoT request definition web app ................. SKIPPED
[INFO] OpenIoT request presentation web app ............... SKIPPED
[INFO] OpenIoT RDF Sensor Schema Editor ................... SKIPPED
[INFO] OpenIoT ............................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21:38 min
[INFO] Finished at: 2015-01-30T15:39:08+08:00
[INFO] Final Memory: 69M/281M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project security.management: Could not resolve
 dependencies for project org.openiot:security.management:war:0.0.1: Failed to c
ollect dependencies at org.primefaces.extensions:all-themes:pom:1.0.8 -> org.pri
mefaces.themes:afterdark:jar:1.0.8: Failed to read artifact descriptor for org.p
rimefaces.themes:afterdark:jar:1.0.8: Could not transfer artifact org.primefaces
.themes:afterdark:pom:1.0.8 from/to prime-repo (http://repository.primefaces.org
): Failed to transfer file: http://repository.primefaces.org/org/primefaces/them
es/afterdark/1.0.8/afterdark-1.0.8.pom. Return code is: 504 , ReasonPhrase:Gatew
ay Timeout. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyReso
lutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

Did I need install something else or set some export or........

thanks

**Comment by hylkevds** [comment]
Ah, it seems the primefaces.org website and repository are down.
I've zipped up the primefaces folder from my local maven repository. Can you try unpacking that to your `.m2/repository` directory and try again?

https://owncloud02.iosb.fraunhofer.de/owncloud/public.php?service=files&t=dd4fa395fa8b7a86f128c521ac556719

**Comment by fcuwang** [comment]
Sir, i unpacked that to .m2/repository/org and try again,but it had new error.

[INFO] Running JiBX binding compiler (single-module mode) on 2 binding file(s)
Running binding compiler version jibx_1_2_5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] OpenIoT Common files ............................... SUCCESS [  1.791 s]
[INFO] OpenIoT Security Client ............................ SUCCESS [  4.294 s]
[INFO] OpenIoT LSM-light Client ........................... SUCCESS [  7.509 s]
[INFO] OpenIoT Security server ............................ SUCCESS [ 14.529 s]
[INFO] OpenIoT security management web app ................ SUCCESS [ 35.517 s]
[INFO] OpenIoT LSM-light Server ........................... SUCCESS [ 25.764 s]
[INFO] xgsn ............................................... FAILURE [ 47.256 s]
[INFO] OpenIoT sdum.core .................................. SKIPPED
[INFO] OpenIoT sdum.client ................................ SKIPPED
[INFO] OpenIoT Scheduler Core ............................. SKIPPED
[INFO] OpenIoT Scheduler Client ........................... SKIPPED
[INFO] OpenIoT ide.core ................................... SKIPPED
[INFO] OpenIoT request definition/presentation commons .... SKIPPED
[INFO] OpenIoT request definition web app ................. SKIPPED
[INFO] OpenIoT request presentation web app ............... SKIPPED
[INFO] OpenIoT RDF Sensor Schema Editor ................... SKIPPED
[INFO] OpenIoT ............................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:17 min
[INFO] Finished at: 2015-01-30T17:28:26+08:00
[INFO] Final Memory: 92M/703M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jibx:maven-jibx-plugin:1.2.5:bind (default) o
n project xgsn: Error loading class java.lang.CharSequence: Error reading path j
ava/lang/CharSequence.class for class java.lang.CharSequence -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE
xception
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :xgsn

thanks.

**Comment by hylkevds** [comment]
Could you try `mvn clean install` ? that will first clean out anything left over from any failed previous build.

**Comment by fcuwang** [comment]
Sir, i tried  mvn clean install but it have same error.

**Comment by hylkevds** [comment]
Which version of Java are you using? Googling that error turns up lots of hits reporting problems with Java 8.

**Comment by fcuwang** [comment]
It's working now!!!  
Thank you so much, sir.   You really help me a lot.
